import 'package:flutter/material.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedstartseitewidget/generated/GeneratedButtonMediumFilledPrimaryBlueWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedstartseitewidget/generated/GeneratedButtonMediumFilledPrimaryBlueWidget1.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedstartseitewidget/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedstartseitewidget/generated/GeneratedRectangle1Widget.dart';

/* Frame Startseite
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedStartseiteWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 58, 159, 165),
                ),
              ),
              Positioned(
                left: 71.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 225.0,
                height: 225.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 68.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 167.0,
                child: GeneratedFrame1Widget(),
              ),
              Positioned(
                left: 111.0,
                top: 371.0,
                right: null,
                bottom: null,
                width: 154.0,
                height: 40.0,
                child: GeneratedButtonMediumFilledPrimaryBlueWidget(),
              ),
              Positioned(
                left: 111.0,
                top: 437.0,
                right: null,
                bottom: null,
                width: 154.0,
                height: 40.0,
                child: GeneratedButtonMediumFilledPrimaryBlueWidget1(),
              )
            ]),
      ),
    ));
  }
}
