import 'package:flutter/material.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedregistrierungwidget/generated/GeneratedFahrtenbuchSMARTWidget1.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedregistrierungwidget/generated/GeneratedDefaultWidget19.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedregistrierungwidget/generated/GeneratedDefaultWidget7.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedregistrierungwidget/generated/GeneratedDefaultWidget18.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedregistrierungwidget/generated/GeneratedCreditCardWidget1.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedregistrierungwidget/generated/GeneratedCreditCardWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedregistrierungwidget/generated/GeneratedRegisterWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedregistrierungwidget/generated/GeneratedSingleButtonWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedregistrierungwidget/generated/GeneratedSurfaceWidget13.dart';

/* Frame Registrierung
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegistrierungWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 39.0,
                child: GeneratedFahrtenbuchSMARTWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 166.0,
                right: null,
                bottom: null,
                width: 333.0,
                height: 184.0,
                child: GeneratedRegisterWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 65.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 37.0,
                child: GeneratedDefaultWidget7(),
              ),
              Positioned(
                left: 16.0,
                top: 439.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 131.0,
                child: GeneratedCreditCardWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 569.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 64.0,
                child: GeneratedSingleButtonWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 342.0,
                right: null,
                bottom: null,
                width: 333.0,
                height: 113.0,
                child: GeneratedCreditCardWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 103.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 56.0,
                child: GeneratedDefaultWidget18(),
              ),
              Positioned(
                left: 183.0,
                top: 127.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 26.0,
                child: GeneratedSurfaceWidget13(),
              ),
              Positioned(
                left: 182.0,
                top: 103.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 56.0,
                child: GeneratedDefaultWidget19(),
              )
            ]),
      ),
    ));
  }
}
