import 'package:flutter/material.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget1/generated/GeneratedFrame11Widget1.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget1/generated/GeneratedFrame10Widget1.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget1/generated/GeneratedIconicRightAccentWidget3.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget1/generated/GeneratedFrame2Widget8.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget1/generated/GeneratedFrame1Widget5.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget1/generated/GeneratedFrame17Widget1.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget1/generated/GeneratedSurfaceWidget72.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget1/generated/GeneratedMobileTopBarDarkWidget11.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget1/generated/GeneratedFrame16Widget5.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget1/generated/GeneratedFrame15Widget1.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget1/generated/GeneratedFrame12Widget1.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget1/generated/GeneratedFrame3Widget5.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget1/generated/GeneratedSubtitleWidget68.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget1/generated/GeneratedSubtitleWidget78.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget1/generated/GeneratedFrame9Widget1.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget1/generated/GeneratedFrame4Widget1.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget1/generated/GeneratedPatternsLabeledDark4itemsWidget11.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget1/generated/GeneratedSurfaceWidget69.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget1/generated/GeneratedSubtitleWidget79.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget1/generated/GeneratedFrame2Widget6.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget1/generated/GeneratedFrame13Widget1.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget1/generated/GeneratedFrame14Widget1.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget1/generated/GeneratedFrame3Widget6.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget1/generated/GeneratedIconicRightAccentWidget4.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget1/generated/GeneratedFrame2Widget7.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget1/generated/GeneratedFrame5Widget1.dart';

/* Frame Neue Fahrt
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNeueFahrtWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 77.0,
                child: GeneratedMobileTopBarDarkWidget11(),
              ),
              Positioned(
                left: 2.0,
                top: 71.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 43.0,
                child: GeneratedFrame1Widget5(),
              ),
              Positioned(
                left: 2.0,
                top: 136.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 43.0,
                child: GeneratedFrame2Widget6(),
              ),
              Positioned(
                left: 11.0,
                top: 280.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 33.0,
                child: GeneratedIconicRightAccentWidget3(),
              ),
              Positioned(
                left: 202.0,
                top: 83.0,
                right: null,
                bottom: null,
                width: 148.0,
                height: 26.0,
                child: GeneratedFrame2Widget7(),
              ),
              Positioned(
                left: 262.0,
                top: 83.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 26.0,
                child: GeneratedFrame3Widget5(),
              ),
              Positioned(
                left: 2.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 43.0,
                child: GeneratedFrame2Widget8(),
              ),
              Positioned(
                left: 2.0,
                top: 352.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 40.0,
                child: GeneratedFrame9Widget1(),
              ),
              Positioned(
                left: 14.0,
                top: 456.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 31.0,
                child: GeneratedSubtitleWidget68(),
              ),
              Positioned(
                left: 0.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 206.0,
                height: 42.0,
                child: GeneratedFrame11Widget1(),
              ),
              Positioned(
                left: 203.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 147.0,
                height: 39.0,
                child: GeneratedFrame12Widget1(),
              ),
              Positioned(
                left: 1.0,
                top: 380.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 76.0,
                child: GeneratedFrame10Widget1(),
              ),
              Positioned(
                left: 2.0,
                top: 191.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 43.0,
                child: GeneratedFrame3Widget6(),
              ),
              Positioned(
                left: 2.0,
                top: 226.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 42.0,
                child: GeneratedFrame4Widget1(),
              ),
              Positioned(
                left: 102.0,
                top: 234.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 25.0,
                child: GeneratedSurfaceWidget69(),
              ),
              Positioned(
                left: 171.0,
                top: 226.0,
                right: null,
                bottom: null,
                width: 176.0,
                height: 42.0,
                child: GeneratedFrame5Widget1(),
              ),
              Positioned(
                left: 2.0,
                top: 284.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 43.0,
                child: GeneratedFrame13Widget1(),
              ),
              Positioned(
                left: 2.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 42.0,
                child: GeneratedFrame14Widget1(),
              ),
              Positioned(
                left: 102.0,
                top: 327.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 25.0,
                child: GeneratedSurfaceWidget72(),
              ),
              Positioned(
                left: 171.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 176.0,
                height: 42.0,
                child: GeneratedFrame15Widget1(),
              ),
              Positioned(
                left: 16.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 31.0,
                child: GeneratedSubtitleWidget78(),
              ),
              Positioned(
                left: -1.0,
                top: 576.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 64.0,
                child: GeneratedPatternsLabeledDark4itemsWidget11(),
              ),
              Positioned(
                left: 16.0,
                top: 263.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 31.0,
                child: GeneratedSubtitleWidget79(),
              ),
              Positioned(
                left: 16.0,
                top: 522.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 48.0,
                child: GeneratedIconicRightAccentWidget4(),
              ),
              Positioned(
                left: 326.0,
                top: 174.0,
                right: null,
                bottom: null,
                width: 21.0,
                height: 20.0,
                child: GeneratedFrame16Widget5(),
              ),
              Positioned(
                left: 326.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 21.0,
                height: 20.0,
                child: GeneratedFrame17Widget1(),
              )
            ]),
      ),
    ));
  }
}
